#!/usr/bin/perl
#
# dorpm
# John Jacobsen, NPX Designs, Inc., jacobsen\@npxdesigns.com
# Started: Tue Jul 12 23:00:28 2005
# Modified for DOMCal by John Kelley, jkelley@icecube.wisc.edu 

use strict;
sub usage;

if ( $#ARGV != 0 ) { die usage; }
print "Welcome to $0.\n";

my $verfile = shift; die "$verfile not found!\n" unless -f $verfile;
my $verstring = `cat $verfile`;
die "Corrupt version file $verfile!\n" unless $verstring =~ /\"(\S+)\"/;
my $version = $1;
die usage unless defined $version;
print "Version is $version.\n";
my $rpmver = $version; 
$rpmver =~ s/^V//; 
$rpmver =~ s/\-/\./g;
$rpmver =~ s/\!//g;

my $rpmname = "domcal-surface";
my $srcdir = "dom-cal";

# RPM build area
my $RPM_ROOT = "$ENV{HOME}/rpmbuild";

chdir "../.." or die "Can't cd .. : $!\n";

my $r;
$r = `rm -rf $rpmname-$rpmver 2>&1`; die "$r\n" unless $r eq "";
$r = `cp -Rp $srcdir $rpmname-$rpmver 2>&1`; die "$r\n" unless $r eq "";
$r = `tar czf /tmp/$rpmname-$rpmver.tgz --exclude=$rpmname-$rpmver/.svn $rpmname-$rpmver 2>&1`;
die "$r\n" unless $r eq "";
$r = `cp /tmp/$rpmname-$rpmver.tgz ${RPM_ROOT}/SOURCES 2>&1`; die "$r\n" unless $r eq "";
$r = `cp $rpmname-$rpmver/surface/$rpmname.spec ${RPM_ROOT}/SPECS/$rpmname-$rpmver.spec 2>&1`; die "$r\n" unless $r eq "";
chdir "${RPM_ROOT}" or die "Can't cd to ${RPM_ROOT}: $!\n";
system "rpmbuild -ba -D 'VER $rpmver' -D 'REL 0' SPECS/$rpmname-$rpmver.spec 2>&1";
print $r;
$r = `rm -rf $rpmname-$rpmver 2>&1`; die "$r\n" unless $r eq "";

exit;

sub usage { 
    return <<EOF;
Usage: $0 <version>
EOF
;
}
__END__

