#!/bin/bash
YEAR="0000"
DAY="0000"
if [ $# -eq 0 ]
then
	echo "Missing year and day"
	exit 1
fi
if [ $# -eq 1 ]
then
	YEAR=`date +%Y`
	DAY=$1
	echo "Assuming that the year in question is $YEAR"
fi
if [ $# -eq 2 ]
then
	YEAR=$1
	DAY=$2
fi
DOMCALDIR="/data/exp/IceCube/$YEAR/calibration/DOMCal-compressed/"
if [ ! -d "$DOMCALDIR$DAY" ] ; then
	echo "$DOMCALDIR$DAY does not appear to be a real directory; aborting"
	exit 1
fi
echo "Marking $DOMCALDIR$DAY as vetted"
echo "$YEAR$DAY" >> ~/.DOMCal_done
